// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqo5ZDUeBUZhoTxiHb-AamzCNfdx-Mms',
    appId: '1:51452883676:web:7c93280aba9a30654fba19',
    messagingSenderId: '51452883676',
    projectId: 'safewalk-59ae7',
    authDomain: 'safewalk-59ae7.firebaseapp.com',
    storageBucket: 'safewalk-59ae7.firebasestorage.app',
    measurementId: 'G-QMR96HK0XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_lCclZqUFTQcqvY0Lz2RrkCjsFpHNMfs',
    appId: '1:51452883676:android:c2dbd76e74d6a6c84fba19',
    messagingSenderId: '51452883676',
    projectId: 'safewalk-59ae7',
    storageBucket: 'safewalk-59ae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAhrabelZ9oCRI1hqRYYEABbO1rmw7hDc',
    appId: '1:51452883676:ios:fb276f0fdc830a344fba19',
    messagingSenderId: '51452883676',
    projectId: 'safewalk-59ae7',
    storageBucket: 'safewalk-59ae7.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAhrabelZ9oCRI1hqRYYEABbO1rmw7hDc',
    appId: '1:51452883676:ios:fb276f0fdc830a344fba19',
    messagingSenderId: '51452883676',
    projectId: 'safewalk-59ae7',
    storageBucket: 'safewalk-59ae7.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTqo5ZDUeBUZhoTxiHb-AamzCNfdx-Mms',
    appId: '1:51452883676:web:63dd49c2f614c8154fba19',
    messagingSenderId: '51452883676',
    projectId: 'safewalk-59ae7',
    authDomain: 'safewalk-59ae7.firebaseapp.com',
    storageBucket: 'safewalk-59ae7.firebasestorage.app',
    measurementId: 'G-6LF86FQ7BM',
  );
}
